# Generated by Django 4.2.7 on 2023-12-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_item_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='category'),
        ),
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='item', max_length=70),
        ),
    ]
