# Generated by Django 4.2.7 on 2023-12-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0013_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=255), max_length=70),
        ),
    ]
