# Generated by Django 4.2.7 on 2024-01-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0016_cars'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='region',
            field=models.CharField(default='Минская Область', max_length=255),
        ),
    ]
