# Generated by Django 4.2.7 on 2024-02-22 20:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item', '0019_alter_item_created_by_alter_item_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='posts_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
