# Generated by Django 4.2.7 on 2024-03-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0020_item_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_rateable',
            field=models.BooleanField(default=False),
        ),
    ]
