# Generated by Django 4.2.7 on 2024-03-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0022_item_is_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_moderated',
            field=models.BooleanField(default=False),
        ),
    ]
