# Generated by Django 4.2.7 on 2024-03-15 19:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item', '0023_item_is_moderated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='items_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
