# Generated by Django 4.2.7 on 2024-01-07 12:45

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('title',), unique=False, verbose_name='slug'),
        ),
    ]
