# Generated by Django 4.2.7 on 2024-03-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='descr',
            field=models.TextField(default='Description'),
            preserve_default=False,
        ),
    ]
